### ISSUE TITLE
Consider remove modlib dependecy

### ISSUE THREAD

**Issue by BruceMustache** [appgurueu/deathlist#1]
But I thing it adds unnecessary complexity
The mod wasn't approved in whynot because of the code quality
https://github.com/bell07/minetest-game-whynot/issues/28

**Comment by appgurueu** [comment]
Modlib provides multiple crucial utilities which I do not want to duplicate across my mods:

1. Configuration management
2. Logging (which arguably needs to be improved)
3. Misc MT-related stuff, like the inventorycube generator

Instead of removing modlib, I'd rather improve the code quality of modlib.
